# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e3adb026be2a34f203d62197e4ac3460a60c69ff133e5a28b5c67e4b3177a982f8618c4b70c0483356feca73dcc12f1c259581adf259361044d869d1da420a4

test:
  secret_key_base: ce95b20259fec8efe088f8416c26e82084827c99d8c72a46e05414228d6ceec0bc2dd93f6bafd0a26fe31f2cd28f44461d553ca8a645e6b0dec3082aae5b83a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
